-- Client-specific static reference. Native gameplay tables remain untouched.
local addon = WordHunterWoW_Addon
local compat = addon and addon.Compat
if not (compat and compat.GameFlavor) then return end
local flavor = compat.GameFlavor()
if flavor ~= "forever" then return end
WordHunterWoW_EntityDataBySource = WordHunterWoW_EntityDataBySource or {}
local ref = { ["schemaVersion"] = 1, ["sourceLabel"] = "MultiLanguage Forever reference", ["viewLabel"] = "ML Forever", ["referenceOnly"] = true, ["provenance"] = { ["edition"] = "forever", ["locales"] = { ["deDE"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage", ["branch"] = "forever", ["commit"] = "87d8e5f4c904291c24296205df97c9bc96aa6943", ["interface"] = "16001" }, ["enUS"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage", ["branch"] = "forever", ["commit"] = "87d8e5f4c904291c24296205df97c9bc96aa6943", ["interface"] = "16001" } } }, ["counts"] = { ["item"] = { ["deDE"] = { ["records"] = 22896, ["text"] = 22099, ["role"] = 0, ["unresolvedValues"] = 67, ["sourceRecords"] = 23501, ["excludedDeveloperRecords"] = 605, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 21971, ["text"] = 21861, ["role"] = 0, ["unresolvedValues"] = 59, ["sourceRecords"] = 22558, ["excludedDeveloperRecords"] = 587, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 16957, ["deOnly"] = 5939, ["enOnly"] = 5014, ["pairedText"] = 16179, ["pairedRoles"] = 0 } }, ["npc"] = { ["deDE"] = { ["records"] = 11415, ["text"] = 0, ["role"] = 2302, ["unresolvedValues"] = 0, ["sourceRecords"] = 11495, ["excludedDeveloperRecords"] = 80, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 13091, ["text"] = 0, ["role"] = 2908, ["unresolvedValues"] = 0, ["sourceRecords"] = 13239, ["excludedDeveloperRecords"] = 148, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 11394, ["deOnly"] = 21, ["enOnly"] = 1697, ["pairedText"] = 0, ["pairedRoles"] = 2295 } }, ["spell"] = { ["deDE"] = { ["records"] = 29500, ["text"] = 19052, ["role"] = 0, ["unresolvedValues"] = 208, ["sourceRecords"] = 30066, ["excludedDeveloperRecords"] = 566, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 29086, ["text"] = 19465, ["role"] = 0, ["unresolvedValues"] = 201, ["sourceRecords"] = 29683, ["excludedDeveloperRecords"] = 597, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 24634, ["deOnly"] = 4866, ["enOnly"] = 4452, ["pairedText"] = 16083, ["pairedRoles"] = 0 } } } }
ref.kinds = { item = { deDE = {}, enUS = {} }, npc = { deDE = {}, enUS = {} }, spell = { deDE = {}, enUS = {} } }
WordHunterWoW_EntityDataBySource["multilanguage-forever"] = ref
