-- Client-specific static reference. Native gameplay tables remain untouched.
local addon = WordHunterWoW_Addon
local compat = addon and addon.Compat
if not (compat and compat.GameFlavor) then return end
local flavor = compat.GameFlavor()
local version = GetBuildInfo and GetBuildInfo()
if not ((flavor == "classic" or flavor == "sod" or flavor == "forever") and type(version) == "string" and version:match("^2%.")) then return end
WordHunterWoW_EntityDataBySource = WordHunterWoW_EntityDataBySource or {}
local ref = { ["schemaVersion"] = 1, ["sourceLabel"] = "MultiLanguage TBC reference", ["viewLabel"] = "ML TBC", ["referenceOnly"] = true, ["provenance"] = { ["edition"] = "tbc", ["locales"] = { ["deDE"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage", ["branch"] = "tbc-classic", ["commit"] = "fe999319f2c9c4c3cdd1bc60c8ae711c079b175f", ["interface"] = "20506" }, ["enUS"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage", ["branch"] = "tbc-classic", ["commit"] = "fe999319f2c9c4c3cdd1bc60c8ae711c079b175f", ["interface"] = "20506" } } }, ["counts"] = { ["item"] = { ["deDE"] = { ["records"] = 26563, ["text"] = 26425, ["role"] = 0, ["unresolvedValues"] = 0, ["sourceRecords"] = 27802, ["excludedDeveloperRecords"] = 1239, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 26247, ["text"] = 26115, ["role"] = 0, ["unresolvedValues"] = 0, ["sourceRecords"] = 27481, ["excludedDeveloperRecords"] = 1234, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 26131, ["deOnly"] = 432, ["enOnly"] = 116, ["pairedText"] = 25999, ["pairedRoles"] = 0 } }, ["npc"] = { ["deDE"] = { ["records"] = 17297, ["text"] = 0, ["role"] = 3770, ["unresolvedValues"] = 0, ["sourceRecords"] = 17347, ["excludedDeveloperRecords"] = 50, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 17287, ["text"] = 0, ["role"] = 3768, ["unresolvedValues"] = 0, ["sourceRecords"] = 17337, ["excludedDeveloperRecords"] = 50, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 17259, ["deOnly"] = 38, ["enOnly"] = 28, ["pairedText"] = 0, ["pairedRoles"] = 3766 } }, ["spell"] = { ["deDE"] = { ["records"] = 28086, ["text"] = 19715, ["role"] = 0, ["unresolvedValues"] = 5, ["sourceRecords"] = 28242, ["excludedDeveloperRecords"] = 156, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 28078, ["text"] = 19749, ["role"] = 0, ["unresolvedValues"] = 5, ["sourceRecords"] = 28234, ["excludedDeveloperRecords"] = 156, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 28010, ["deOnly"] = 76, ["enOnly"] = 68, ["pairedText"] = 19685, ["pairedRoles"] = 0 } } } }
ref.kinds = { item = { deDE = {}, enUS = {} }, npc = { deDE = {}, enUS = {} }, spell = { deDE = {}, enUS = {} } }
WordHunterWoW_EntityDataBySource["multilanguage-tbc"] = ref
