-- Generated by Tools/put_voice_in_dictionary.py. Do not edit by hand.
--
-- The word pack lives in the dictionary's own folder, so that the meaning of a
-- word and the sound of it are one addon and one download. The engine builds a
-- clip's path from the folder a pack names here, so naming this one is all it
-- takes -- nothing in the engine knows about this arrangement.
WordHunterWoW_Voice_Parts = WordHunterWoW_Voice_Parts or {}
WordHunterWoW_Voice_Parts["WordHunterWoW-Dictionary-DE"] = { words = true }
