-- Client-specific static reference. Native gameplay tables remain untouched.
local addon = WordHunterWoW_Addon
local compat = addon and addon.Compat
if not (compat and compat.GameFlavor) then return end
local flavor = compat.GameFlavor()
local version = GetBuildInfo and GetBuildInfo()
if not ((flavor == "classic" or flavor == "sod" or flavor == "forever") and type(version) == "string" and version:match("^4%.")) then return end
WordHunterWoW_EntityDataBySource = WordHunterWoW_EntityDataBySource or {}
local ref = { ["schemaVersion"] = 1, ["sourceLabel"] = "MultiLanguage Cata reference", ["viewLabel"] = "ML Cata", ["referenceOnly"] = true, ["provenance"] = { ["edition"] = "cata", ["locales"] = { ["enUS"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage", ["branch"] = "cata", ["commit"] = "cc638509ca3347e4c22bf6187dac4c2443b9057d", ["interface"] = "40402" }, ["deDE"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage-de", ["branch"] = "master", ["commit"] = "868743d847392a43bf3b353501432d64db8b8820", ["interface"] = "40402" } } }, ["counts"] = { ["item"] = { ["deDE"] = { ["records"] = 56909, ["text"] = 56759, ["role"] = 0, ["unresolvedValues"] = 65, ["sourceRecords"] = 59565, ["excludedDeveloperRecords"] = 2656, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 56675, ["text"] = 56527, ["role"] = 0, ["unresolvedValues"] = 65, ["sourceRecords"] = 59319, ["excludedDeveloperRecords"] = 2644, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 56675, ["deOnly"] = 234, ["enOnly"] = 0, ["pairedText"] = 56527, ["pairedRoles"] = 0 } }, ["npc"] = { ["deDE"] = { ["records"] = 37372, ["text"] = 0, ["role"] = 7804, ["unresolvedValues"] = 0, ["sourceRecords"] = 37437, ["excludedDeveloperRecords"] = 65, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 41516, ["text"] = 0, ["role"] = 8165, ["unresolvedValues"] = 0, ["sourceRecords"] = 41600, ["excludedDeveloperRecords"] = 84, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 37191, ["deOnly"] = 181, ["enOnly"] = 4325, ["pairedText"] = 0, ["pairedRoles"] = 7688 } }, ["spell"] = { ["deDE"] = { ["records"] = 69510, ["text"] = 42438, ["role"] = 0, ["unresolvedValues"] = 51, ["sourceRecords"] = 69757, ["excludedDeveloperRecords"] = 247, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 69373, ["text"] = 42423, ["role"] = 0, ["unresolvedValues"] = 48, ["sourceRecords"] = 69620, ["excludedDeveloperRecords"] = 247, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 69367, ["deOnly"] = 143, ["enOnly"] = 6, ["pairedText"] = 42365, ["pairedRoles"] = 0 } } } }
ref.kinds = { item = { deDE = {}, enUS = {} }, npc = { deDE = {}, enUS = {} }, spell = { deDE = {}, enUS = {} } }
WordHunterWoW_EntityDataBySource["multilanguage-cata"] = ref
