-- Client-specific static reference. Native gameplay tables remain untouched.
local addon = WordHunterWoW_Addon
local compat = addon and addon.Compat
if not (compat and compat.GameFlavor) then return end
local flavor = compat.GameFlavor()
local version = GetBuildInfo and GetBuildInfo()
if not ((flavor == "classic" or flavor == "sod" or flavor == "forever") and type(version) == "string" and version:match("^5%.")) then return end
WordHunterWoW_EntityDataBySource = WordHunterWoW_EntityDataBySource or {}
local ref = { ["schemaVersion"] = 1, ["sourceLabel"] = "MultiLanguage MoP reference", ["viewLabel"] = "ML MoP", ["referenceOnly"] = true, ["provenance"] = { ["edition"] = "mop-classic", ["locales"] = { ["enUS"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage", ["branch"] = "mop-classic", ["commit"] = "ff01f8cbdd3bd8fd7644fb785dcf1e6f76a28c37", ["interface"] = "50502" }, ["deDE"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage-de", ["branch"] = "mop-classic", ["commit"] = "a9e7ba2d7b8654481abbd70f7190b341346c68eb", ["interface"] = "50502" } } }, ["counts"] = { ["item"] = { ["deDE"] = { ["records"] = 75770, ["text"] = 75615, ["role"] = 0, ["unresolvedValues"] = 29, ["sourceRecords"] = 79394, ["excludedDeveloperRecords"] = 3624, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 75569, ["text"] = 75417, ["role"] = 0, ["unresolvedValues"] = 29, ["sourceRecords"] = 79181, ["excludedDeveloperRecords"] = 3612, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 75529, ["deOnly"] = 241, ["enOnly"] = 40, ["pairedText"] = 75376, ["pairedRoles"] = 0 } }, ["npc"] = { ["deDE"] = { ["records"] = 45568, ["text"] = 0, ["role"] = 9295, ["unresolvedValues"] = 0, ["sourceRecords"] = 45636, ["excludedDeveloperRecords"] = 68, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 54546, ["text"] = 0, ["role"] = 10266, ["unresolvedValues"] = 0, ["sourceRecords"] = 54644, ["excludedDeveloperRecords"] = 98, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 45379, ["deOnly"] = 189, ["enOnly"] = 9167, ["pairedText"] = 0, ["pairedRoles"] = 9178 } }, ["spell"] = { ["deDE"] = { ["records"] = 95829, ["text"] = 54979, ["role"] = 0, ["unresolvedValues"] = 55, ["sourceRecords"] = 95986, ["excludedDeveloperRecords"] = 157, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 95753, ["text"] = 54973, ["role"] = 0, ["unresolvedValues"] = 53, ["sourceRecords"] = 95910, ["excludedDeveloperRecords"] = 157, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 95668, ["deOnly"] = 161, ["enOnly"] = 85, ["pairedText"] = 54888, ["pairedRoles"] = 0 } } } }
ref.kinds = { item = { deDE = {}, enUS = {} }, npc = { deDE = {}, enUS = {} }, spell = { deDE = {}, enUS = {} } }
WordHunterWoW_EntityDataBySource["multilanguage-mop-classic"] = ref
