-- Generated by QuestData/Tools/import_multilanguage_references.py.
-- References require explicit selection; they never merge into native quest buckets.
WordHunterWoW_QuestSources = WordHunterWoW_QuestSources or {}
local sources = WordHunterWoW_QuestSources
do
local addon = WordHunterWoW_Addon
local compat = addon and addon.Compat
local flavor = compat and compat.GameFlavor and compat.GameFlavor()
if flavor and flavor ~= "retail" then
sources["multilanguage-classic-master"] = { label = "MultiLanguage Classic master (Era + seasonal)", sourceFlavor = "classic-master", sourceVersionUnverified = true, bilingualPairVerified = false, voiceUnavailable = true, loaded = false, locales = { deDE = {}, enUS = {} }, localeSources = { deDE = { revision = "c51dc2e5141f070f5b92de190521d79e8dccaeab", repository = "https://github.com/rubenzantingh/MultiLanguage", path = "Database/Quests/deDE.lua", sha256 = "b5d04ea17061d2acf86eb0dfef34d11e8b959aab14d68791de83ccfc43763780" }, enUS = { revision = "c51dc2e5141f070f5b92de190521d79e8dccaeab", repository = "https://github.com/rubenzantingh/MultiLanguage", path = "Database/Quests/enUS.lua", sha256 = "6df300003f6b6b2b0704490e044d90dd8f1be259a3912f677b647d30ce975867" } } }
end
end
do
local version = GetBuildInfo and GetBuildInfo()
if type(version) == "string" and version:match("^2%.") then
sources["multilanguage-tbc"] = { label = "MultiLanguage TBC", sourceFlavor = "tbc", sourceVersionUnverified = true, bilingualPairVerified = false, voiceUnavailable = true, loaded = false, locales = { deDE = {}, enUS = {} }, localeSources = { deDE = { revision = "fe999319f2c9c4c3cdd1bc60c8ae711c079b175f", repository = "https://github.com/rubenzantingh/MultiLanguage", path = "Database/Quests/deDE.lua", sha256 = "cb0e2736097dd1cffcd49dac0a8c7a1884c1f9af97ac7136d5766a1cd51a6143" }, enUS = { revision = "fe999319f2c9c4c3cdd1bc60c8ae711c079b175f", repository = "https://github.com/rubenzantingh/MultiLanguage", path = "Database/Quests/enUS.lua", sha256 = "f910f2faa8a5bf2333ad3a1c077b71171516e10c71697a658666057d18d1c158" } } }
end
end
do
local addon = WordHunterWoW_Addon
local compat = addon and addon.Compat
local flavor = compat and compat.GameFlavor and compat.GameFlavor()
if flavor == "retail" then
sources["multilanguage-retail"] = { label = "MultiLanguage Retail", sourceFlavor = "retail", sourceVersionUnverified = true, bilingualPairVerified = false, voiceUnavailable = true, loaded = false, locales = { deDE = {}, enUS = {} }, localeSources = { deDE = { revision = "a54af98d3013271c6f2cac8c5c00bbf4d74185bd", repository = "https://github.com/rubenzantingh/MultiLanguage-de", path = "Database/Quests/quests.lua", sha256 = "b8492437d9d2cd26eb050f401c54dba0c6c982f79200fd452cab7bd9dd284ebd" }, enUS = { revision = "b2e3b0bf1251f30babdb44545adf3957e94d63f6", repository = "https://github.com/rubenzantingh/MultiLanguage", path = "Database/Quests/quests.lua", sha256 = "adb60075fa4b0223ce2d9a77139833c2417984f401e75ce7e28f2125d12b0a58" } } }
end
end
