-- Client-specific static reference. Native gameplay tables remain untouched.
local addon = WordHunterWoW_Addon
local compat = addon and addon.Compat
if not (compat and compat.GameFlavor) then return end
local flavor = compat.GameFlavor()
local version = GetBuildInfo and GetBuildInfo()
if not ((flavor == "classic" or flavor == "sod" or flavor == "forever") and type(version) == "string" and version:match("^3%.")) then return end
WordHunterWoW_EntityDataBySource = WordHunterWoW_EntityDataBySource or {}
local ref = { ["schemaVersion"] = 1, ["sourceLabel"] = "MultiLanguage Wrath reference", ["viewLabel"] = "ML Wrath", ["referenceOnly"] = true, ["provenance"] = { ["edition"] = "wrath", ["locales"] = { ["enUS"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage", ["branch"] = "wotlk", ["commit"] = "108ede6c1fccfff2d41f291c49a032759a8a76c8", ["interface"] = "30403" }, ["deDE"] = { ["repo"] = "https://github.com/rubenzantingh/MultiLanguage-de", ["branch"] = "historical-last-wotlk", ["commit"] = "a0a5e66931a7f13f06e4f73d1dd472215c5da5a9", ["interface"] = "30403" } } }, ["counts"] = { ["item"] = { ["deDE"] = { ["records"] = 40538, ["text"] = 39001, ["role"] = 0, ["unresolvedValues"] = 74, ["sourceRecords"] = 42360, ["excludedDeveloperRecords"] = 1822, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 40385, ["text"] = 40237, ["role"] = 0, ["unresolvedValues"] = 74, ["sourceRecords"] = 42202, ["excludedDeveloperRecords"] = 1817, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 40382, ["deOnly"] = 156, ["enOnly"] = 3, ["pairedText"] = 38860, ["pairedRoles"] = 0 } }, ["npc"] = { ["deDE"] = { ["records"] = 24593, ["text"] = 0, ["role"] = 5216, ["unresolvedValues"] = 0, ["sourceRecords"] = 24649, ["excludedDeveloperRecords"] = 56, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 26197, ["text"] = 0, ["role"] = 5418, ["unresolvedValues"] = 0, ["sourceRecords"] = 26264, ["excludedDeveloperRecords"] = 67, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 24532, ["deOnly"] = 61, ["enOnly"] = 1665, ["pairedText"] = 0, ["pairedRoles"] = 5211 } }, ["spell"] = { ["deDE"] = { ["records"] = 48253, ["text"] = 34429, ["role"] = 0, ["unresolvedValues"] = 123, ["sourceRecords"] = 48447, ["excludedDeveloperRecords"] = 194, ["omittedEmptyNames"] = 0 }, ["enUS"] = { ["records"] = 48149, ["text"] = 34418, ["role"] = 0, ["unresolvedValues"] = 120, ["sourceRecords"] = 48343, ["excludedDeveloperRecords"] = 194, ["omittedEmptyNames"] = 0 }, ["coverage"] = { ["pairedNames"] = 48147, ["deOnly"] = 106, ["enOnly"] = 2, ["pairedText"] = 34384, ["pairedRoles"] = 0 } } } }
ref.kinds = { item = { deDE = {}, enUS = {} }, npc = { deDE = {}, enUS = {} }, spell = { deDE = {}, enUS = {} } }
WordHunterWoW_EntityDataBySource["multilanguage-wrath"] = ref
